name: Accidental Recipes
favicon: null
layout_spectrum: 0.22073
typography_spectrum: 0.9050296589266509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#bcdceb'
    - '#a4abb3'
    - '#627488'
    - '#2f431e'
  brandStrength: 0.125
  lightness: 0.5932531750295311
  saturation: 0.25
  rhythmicContrast: 0.4351510105188936
purpose: []
